import { useEffect } from "react";
import axios from "axios";

// useEffect(()=>{
// },[])

console.log("cargo los datos")

function DatosDDLs() {

    useEffect(() => {
        console.log("cargo los dato22s")
        //peticiones
    }, [])

    const data = {

        aduanas: [
            { value: 1, label: "0001-ADUANA AMAPALA" },
            { value: 2, label: "0002-ADUANA LA CEIBA" },
            { value: 3, label: "0003-ADUANA PUERTO HENECAN-SN LORENZO" },
            { value: 4, label: "0004-ADUANA PUERTO CORTES" },
            { value: 5, label: "0005-ADUANA PUERTO LEMPIRA" },
            { value: 6, label: "0006-ADUANA ROATAN" },
            { value: 7, label: "0007-GUARDATURA ROATAN" },
            { value: 8, label: "0008-ADUANA TELA" },
            { value: 9, label: "0009-ADUANA PUERTO CASTILLA" },
            { value: 10, label: "0010-GUARDATURA GOLOSON-CEIBA" },
            { value: 11, label: "0011-ADUANA LA MESA" },
            { value: 12, label: "0013-GUARDATURA LA MESA" },
            { value: 13, label: "0014-ADUANA TONCONTIN" },
            { value: 14, label: "0015-GUARDATURA TONCONTIN" },
            { value: 15, label: "0016-PASO FRONTERIZO CORINTO HN-GT" },
            { value: 16, label: "0017-ADUANA PALMEROLA" },
            { value: 17, label: "0018-GUARDATURA PALMEROLA" },
            { value: 18, label: "0020-ADUANA AGUA CALIENTE" },
            { value: 19, label: "0021-ADUANA MOCALEMPA" },
            { value: 20, label: "0022-ADUANA LA CONCORDIA" },
            { value: 21, label: "0023-ADUANA EL AMATILLO" },
            { value: 22, label: "0024-ADUANA EL FLORvalueO" },
            { value: 23, label: "0025-ADUANA EL POY" },
            { value: 24, label: "0027-ADUANA LA FRATERNvalueAD" },
            { value: 25, label: "0029-ADUANA GUASAULE" },
            { value: 26, label: "0034-ADUANA LAS MANOS" },
            { value: 27, label: "3004-ADUANA TECUN UMAN" },
            { value: 28, label: "6001-ZOLI PUERTO CORTES" },
            { value: 29, label: "6003-ZOLI INHDELVA" },
            { value: 30, label: "6005-CONSTRUCCIONES Y DESARROLLOS VICTOR" },
            { value: 31, label: "6011-HONDURAS AMERICAN TABACO SA (HATSA)" },
            { value: 32, label: "6012-CONFECCIONES INTERNACIONALES S.A. DE C.V." },
            { value: 33, label: "6013-ZOLI NOVEM CAR" },
            { value: 34, label: "6017-ZOLI DELI DE HONDURAS S.A. DE C.V." },
            { value: 35, label: "6021-ZOLI EMPACADORA DE CAMARONES SANTA INES" },
            { value: 36, label: "6022-ZOLI EMPACADORA DE PRODUCTO ACUATICOS SAN LORENZO" },
            { value: 37, label: "6023-ZOLI HATSA (DANLI)" },
            { value: 38, label: "6029-ZOLI CONFECCIONES MONZINI S.A." },
            { value: 39, label: "6030-ZOLI METROPOLITANA JACALEAPA" },
            { value: 40, label: "6035-ZOLI ORVASA" },
            { value: 41, label: "6043-ZOLI COMPONENTES ELECTRONICOS" },
            { value: 42, label: "6045-ZOLI CLASIF. Y EXPORT. TABACO" },
            { value: 43, label: "6047-ZOLI IBEROAMERICANA DE MARISCO" },
            { value: 44, label: "6048-ZOLI CARACOL KNITS" },
            { value: 45, label: "6056-ASTRO CARTON HONDURAS SA DE CV" },
            { value: 46, label: "6059-ZOLI MANUFACTURERA CEIBEÑA" },
            { value: 47, label: "6060-ZOLI ATUTO" },
            { value: 48, label: "6064-ZOLI TABACOS DE DANLI" },
            { value: 49, label: "6065-ZOLI COTTONWISE TEXTILES HOND." },
            { value: 50, label: "6067-ZOLI WOONG CHUN HOND.S.A." },
            { value: 51, label: "6068-ZONA LIBRE HONDURAS SA DE CV" },
            { value: 52, label: "6073-ZOLI ZIP SAN MIGUEL VI" },
            { value: 53, label: "6074-PARQUE INDUSTRIAL BUFALO S.A." },
            { value: 54, label: "6075-GRUPO J SOCIEDAD ANONIMA" },
            { value: 55, label: "6077-ZONA INDUSTRIAL DE EXPORTACION BUENAVISTA SA" },
            { value: 56, label: "6078-ZOLI ZIP CHOLOMA" },
            { value: 57, label: "6079-ZIP EL PORVENIR" },
            { value: 58, label: "6083- ZOLI LEAR AUTOMOTIVE EDDS, HOND." },
            { value: 59, label: "6085-ZOLI ZIP SAN JOSE" },
            { value: 60, label: "6091-ZOLI GRANDWAY HONDURAS, S. DE R.L." },
            { value: 61, label: "6093-ZOLI U.S. YACHTS S. DE R.L." },
            { value: 62, label: "6095-ZOLI ZIP CALPULES" },
            { value: 63, label: "6100-ZOLI AQUAFINCA ST. PETER FISH" },
            { value: 64, label: "6102-AEREO -IMPEX S.A." },
            { value: 65, label: "6103-ZOLI C.B.I., S.A." },
            { value: 66, label: "6106-ZOLI. CIA. OPERAD.ZIP RIO BLANCO" },
            { value: 67, label: "6107-ZOLI EMPACADORA LITORAL, S.A." },
            { value: 68, label: "6108-NEW HOLLAND LINGERIE DE HONDURAS SA" },
            { value: 69, label: "6109-ZOLI AMERICA S.A. DE C.V." },
            { value: 70, label: "6110-ZOLI AGENCIA J. E HANDAL S.A DE C.V" },
            { value: 71, label: "6114-ZOLI PARQUE INDUSTRIAL REAL" },
            { value: 72, label: "6118-ZOLI HONDURAS ELECT. DISTRIB. SYST." },
            { value: 73, label: "6121-ZOLI S. HONDURAS" },
            { value: 74, label: "6125-ZOLI GAS DEL CARIBE, S.A. DE C.V." },
            { value: 75, label: "6126-ZOLI INVERSIONES EL CACAO" },
            { value: 76, label: "6129-ZOLI  R.L.A. MANUFACTURING, SRL" },
            { value: 77, label: "6131-ZOLI FARM FRESH, S.A." },
            { value: 78, label: "6132-ZOLI ZINMA EXPORT" },
            { value: 79, label: "6136-ZOLI GOLFO AZUL" },
            { value: 80, label: "6137-ZOLI BANG SAN  HONDURAS, S. DE R.L." },
            { value: 81, label: "6138-ZOLI MICROENVASES" },
            { value: 82, label: "6142-ZOLI FOSFORERA CENTROAMERICANA" },
            { value: 83, label: "6143-ZOLI  ALAMODE S.A." },
            { value: 84, label: "6145-ZOLI TEXTILE SUPLY SERVICE S.ADE CV" },
            { value: 85, label: "6146-ZOLI INVERSIONISTAS Y EXPORTADORES" },
            { value: 86, label: "6148-ZOLI H.M.M DE HONDURAS S.A DE C.V" },
            { value: 87, label: "6149-ZOLI YODECO DE HONDURAS S A BUFALO" },
            { value: 88, label: "6154-ZOLI YODECO (YORO)" },
            { value: 89, label: "6155-ZOLI YODECO DE HONDURAS S.A OLANCHO" },
            { value: 90, label: "6159-ZOLI EL POLVORIN, S.A. DE C.V." },
            { value: 91, label: "6160-AEREO -IMPEX S.A." },
            { value: 92, label: "6161-ZOLI PRvalueE, S.A. DE C.V." },
            { value: 93, label: "6162-ZOLI SER.PROF. MADERA (SERPROMA)" },
            { value: 94, label: "6163-ZOLI TECNOSUPPLIER S. DE R.L." },
            { value: 95, label: "6164-ZONA INDUST. DE EXPORT. CHOLOMA II" },
            { value: 96, label: "6165-ZOLI ZIP AMARATECA" },
            { value: 97, label: "6166-ZOLI GREEN VALLEY INDUSTRIAL PARK" },
            { value: 98, label: "6169-NOVA CHEM S DE RL DE CV" },
            { value: 99, label: "6172-ZOLI J.C. INTERNAT. INDUST. LAUNDRY" },
            { value: 100, label: "6175-ZOLI ALIMENTOS CONCENTRADOS  NACI." },
            { value: 101, label: "6176-ZOLI MADERAS DE AMERICA" },
            { value: 102, label: "6177-ZOLI VESTA TRADING SA" },
            { value: 103, label: "6178-ZOLI MARTEX FIBER INTERNATIONAL SRL" },
            { value: 104, label: "6179-ZOLI CENTRAL TEXTILES" },
            { value: 105, label: "6180-ZOLI LA FLOR DE COPAN SAS" },
            { value: 106, label: "6182-ZOLI DE SULA S.A." },
            { value: 107, label: "6184-ZOLI MARISCOS PERLA MAR, SRL" },
            { value: 108, label: "6185-ZOLI INVERSIONES MATERIALES, SRL" },
            { value: 109, label: "6186-ZOLI GILDAN HOND. HOSIERY FACTORY" },
            { value: 110, label: "6187-ZOLI GILDAN CHOLOMA TEXTILES, S.A." },
            { value: 111, label: "6188-RECYCLERS GROUP OF HONDURAS S DE R" },
            { value: 112, label: "6191-ZOLI MANUFACTURAS DEL TROPICO" },
            { value: 113, label: "6194-ZOLI EXPORT. DE CALvalueAD DE HOND." },
            { value: 114, label: "6196-ZOLI INVERSIONES AMALGAMADAS" },
            { value: 115, label: "6197-ZOLI MOUNT DORA FARMS HONDURAS" },
            { value: 116, label: "6200-ZOLI MARINOS PESCADERIA, SRL" },
            { value: 117, label: "6201-ZOLI HANIL HONDURAS, S.A. DE C.V." },
            { value: 118, label: "6205-ZOLI PARQUES E INVER. INDUSTRIALES" },
            { value: 119, label: "6208-ZOLI HARNES CONT. EQUIPMENT HOND." },
            { value: 120, label: "6209-ZOLI FORMAS TERMICAS, S.A. DE C.V." },
            { value: 121, label: "6210-ENERGIA Y VAPOR S.A. DE C.V." },
            { value: 122, label: "6211-ZOLI ACEITES Y DERIVADOS, S.A." },
            { value: 123, label: "6212-ZOLI CORUMO INTERNACIONAL, SRL" },
            { value: 124, label: "6215-ZOLI AGROINDUSTRIAL PALMA REAL" },
            { value: 125, label: "6216-ZOLI AGRICOLA INDUSTRIAL CEIBEÑA S." },
            { value: 126, label: "6218-ZOLI ALTIA BUSINESS PARK" },
            { value: 127, label: "6219-ZOLI  VOGUE CORPORATION INTERNATIO." },
            { value: 128, label: "6220-ZOLI  SCANDINAVIAN TOBACCO GROUP" },
            { value: 129, label: "6221-ZOLI RECICLAJE DIAMANTE" },
            { value: 130, label: "6222-ZOLI MANUCHAR HONDURAS" },
            { value: 131, label: "6223-S & P RECICLYNG HONDURAS S.A. DE" },
            { value: 132, label: "6225-PALMAS CENTROAMERICANAS (PALCASA)" },
            { value: 133, label: "6226-HENDRIX AND DAIL DE HONDURAS SA" },
            { value: 134, label: "6227-RM SEWING SUPPLY, S. DE R. L." },
            { value: 135, label: "6228-ZONA LIBRE ST ANDRREWS S.A. DE C.V." },
            { value: 136, label: "6229-METALES Y ALEACIONES S A DE C V" },
            { value: 137, label: "6230-CHEMICAL MANUFACTURING AND EXPORTIN" },
            { value: 138, label: "6231-ZOLI ALMACEN FISCAL P SA DE CV" },
            { value: 139, label: "6232-ZONA LIBRE LAS AMERICAS SA DE CV" },
            { value: 140, label: "6233-NOVA HONDURAS ZONA LIBRE SA" },
            { value: 141, label: "6234-NEW HOLLAND LINGERIE DE HONDURAS" },
            { value: 142, label: "6235-CENTRAL AMERICAN TRAILER REPAIR SRL" },
            { value: 143, label: "6236-HONDURAS CONTAINER SERVICE SA DE CV" },
            { value: 144, label: "6237-ELASTICOS CENTROAMERICANOS Y TEXTIL" },
            { value: 145, label: "6238-ELASTICOS CENTROAMERICANOS SA DE CV" },
            { value: 146, label: "6239-GENESIS APPAREL" },
            { value: 147, label: "6240-HILOS A&E DE HONDURAS" },
            { value: 148, label: "6241-INVERSIONES LAS FLORES" },
            { value: 149, label: "6242-RIO NANCE AGRO-INDUSTRIAL SA DE CV" },
            { value: 150, label: "6244-INDUSTRIA HONDUREÑA DE MECHAS SA CV" },
            { value: 151, label: "6245-ARTESANOS SA DE CV" },
            { value: 152, label: "6246-FIBRAS Y TEXTILES SA DE CV" },
            { value: 153, label: "6247-YKK HONDURAS SA" },
            { value: 154, label: "6248-EUROMODAS SA" },
            { value: 155, label: "6249-CAOBA D EHONDURAS SA D ECV" },
            { value: 156, label: "6251-WINTEX DE HONDURAS SA DE CV" },
            { value: 157, label: "6253-INDUSTRIAS CONTINENTAL S DE RL" },
            { value: 158, label: "6254-TECNO SUPPLIER SA DE CV" },
            { value: 159, label: "6255-INVERSIONES LA VICTORIA" },
            { value: 160, label: "6256-COFRADIA INDUSTRIAL PARK SA" },
            { value: 161, label: "6257-CIRSA HONDURAS S DE RL DE CV" },
            { value: 162, label: "6258-RECYCLERS GROUP OF HONDURAS S DE R" },
            { value: 163, label: "6259-GRUPO INDUSTRIAL RIO BLANQUITO SA" },
            { value: 164, label: "6260-ELECTROQUIMICA DE HONDURAS SA" },
            { value: 165, label: "6261-MAQUILA Y CONFECCIONES AXIvalue INTERN" },
            { value: 166, label: "6262-SJ MARIOL SA DE CV" },
            { value: 167, label: "6263-PALMA DEL BAJO AGUAN SA" },
            { value: 168, label: "6264-ETHAN ALLEN SA" },
            { value: 169, label: "6265-RECICLAJE Y METALES DE CORTES S RL" },
            { value: 170, label: "6267-TABACOS DEL ORIENTE S DE RL" },
            { value: 171, label: "6269-AQUAFEED SA DE CV" },
            { value: 172, label: "6270-HILOS Y MECHAS SA DE CV" },
            { value: 173, label: "6271-C Y D S.A. DE C.V." },
            { value: 174, label: "6272-AGROINDUSTRIAL DEL VALLE S A" },
            { value: 175, label: "6273-FARM FRESH SA - LA PAZ" },
            { value: 176, label: "6274-FARM FRESH SA - COMAYAGUA" },
            { value: 177, label: "6275-PESCA DEL ATLANTICO S DE RL" },
            { value: 178, label: "6276-ADMINISTRACION DE CALL CENTERS, S.A" },
            { value: 179, label: "6277-INVERSIONES EMCO SA DE CV" },
            { value: 180, label: "6278-AGROECOLOGICA INTERNACIONAL S DE RL" },
            { value: 181, label: "6279-CHOCOLATE DEL CARIBE S.A." },
            { value: 182, label: "6280-CONVERTvalueORA DE FIBRAS SA DE CV" },
            { value: 183, label: "6281-SOLUCIONES QUIMICAS INDUSTRIALES SA" },
            { value: 184, label: "6282-PRODUCTOS FRESCOS DEL MAR SN CARLOS" },
            { value: 185, label: "6283-EXTRUM SA DE CV" },
            { value: 186, label: "6284-DICKIES DE HONDURAS SA" },
            { value: 187, label: "6285-ALUCOM INTERNATIONAL S A DE C V" },
            { value: 188, label: "6286-PALMEROS DEL AGUAN SA (PALMASA)" },
            { value: 189, label: "6287-NUTRIAVES SA DE CV" },
            { value: 190, label: "6288-RECYCLERS GROUP OF HONDURAS S DE R" },
            { value: 191, label: "6289-REPLAST DE HONDURAS S DE RL" },
            { value: 192, label: "6290-PROCESA SA DE CV" },
            { value: 193, label: "6291-GRUPO RODRIGUEZ" },
            { value: 194, label: "6292-ZONA LIBRE LAS AMERICAS SA DE CV" },
            { value: 195, label: "6293-HILOTEX, S.A. DE C.V." },
            { value: 196, label: "6294-MOLINOS DE HONDURAS, SA" },
            { value: 197, label: "6295-BESCO S DE R L" },
            { value: 198, label: "6296-INDUSTRIAS CARNEAS DEL SUR SA" },
            { value: 199, label: "6297-ZOLI JAMEE EXPORT, S.A." },
            { value: 200, label: "6298-FORESTAL LATINOAMERICANA SA DE CV" },
            { value: 201, label: "6299-ZOLI EXPORTADORA  SAMOA" },
            { value: 202, label: "6300-ARNESES Y ENSAMBLES S DE RL" },
            { value: 203, label: "6301-O. R. S. DE HONDURAS S. DE R. L." },
            { value: 204, label: "6302-EXPORTADORA ECO INDUSTRIAL SA DE C" },
            { value: 205, label: "6303-COMPAÑIA INTERNACIONAL DE CONFECCIO" },
            { value: 206, label: "6304-LOS ROBLES SA DE CV" },
            { value: 207, label: "6305-INDUSTRIAS CONTINENTAL S DE RL" },
            { value: 208, label: "6306-SISTEMAS DE ENERGIA DE HONDURAS SA" },
            { value: 209, label: "6307-FLAMES INTERNATIONAL S DE RL" },
            { value: 210, label: "6308-PALMAS INTERNATIONAL SA DE CV" },
            { value: 211, label: "6309-PARQUE INDUSTRIAL DE CHOLIMA SA" },
            { value: 212, label: "6310-SANITARIOS CAIRO SA" },
            { value: 213, label: "6311-SADELCA DE HONDURAS S DE RL" },
            { value: 214, label: "6312-YKK HONDURAS SA DE CV" },
            { value: 215, label: "6313-EUROMODAS SA" },
            { value: 216, label: "6314-CAOBA DE HONDURAS SA DE CV" },
            { value: 217, label: "6315-CORPORACION CARTONERA & IMPRESOS 3J" },
            { value: 218, label: "6316-BIOCOMBUSTIBLES Y SALUD S A DE C" },
            { value: 219, label: "6317-SAN JUAN INNOVATION PARK SA DE CV" },
            { value: 220, label: "6318-PRvalueE PERFORMANCE FABRICS, S.A. DE" },
            { value: 221, label: "6320-CIA AGRICOLA IND CEIBEÑA S A DE CV" },
            { value: 222, label: "6321-ALMACENADORA DE MATERIALES A GRANEL" },
            { value: 223, label: "6322-GUAYACAN FARMS S A DE C V" },
            { value: 224, label: "6323-PROGRESSIVE ENERGY CORPORATION SA D" },
            { value: 225, label: "6324-Q-APPAREL, SOCIEDAD ANONIMA" },
            { value: 226, label: "6325-BIOLARVA AQUACULTURE SA" },
            { value: 227, label: "6326-BIOLARVA AQUACULTURE SA" },
            { value: 228, label: "6327-INVERSIONES MI PULPE S DE R L" },
            { value: 229, label: "6328-LEVANTER SA DE CV" },
            { value: 230, label: "6329-ALMACENADORA DE MATERIALES A GRANEL" },
            { value: 231, label: "6330-REMA S.A." },
            { value: 232, label: "6331-FABRICA HONDUREÑA DE RECICLAJE S" },
            { value: 233, label: "6332-GRAN COSTA HONDURAS S DE R L" },
            { value: 234, label: "6333-BENEFICIO DE CAFE INLOHER S DE RL" },
            { value: 235, label: "6334-CARIBBEAN APPETIZERS SA DE CV" },
            { value: 236, label: "6335-SAN SERVICES S DE RL DE CV" },
            { value: 237, label: "6336-CYGNUS PACIFIC S A DE C V" },
            { value: 238, label: "6337-TABLEROS DE HONDURAS SA DE CV" },
            { value: 239, label: "6338-LEVANTER SA DE CV" },
            { value: 240, label: "6339-BIJAO ELECTRIC COMPANY SA DE C.V" },
            { value: 241, label: "6340-INHDELVA SPS S.A. DE C.V." },
            { value: 242, label: "6341-GILDAN HONDURAS PROPERTIES S DE R L" },
            { value: 243, label: "6342-INGENIERIA OPERACION PLANTAS TRATAM" },
            { value: 244, label: "6343-INVERSIONES ECOTEK SOCIEDAD ANONIMA" },
            { value: 245, label: "6344-EXPORTADORA E IMPORTADORA LA SIRENA" },
            { value: 246, label: "6345-CORAL BAY SA DE CV" },
            { value: 247, label: "6346-COFFEE PLANET CORPORATION SA DE CV" },
            { value: 248, label: "6347-ZONA LIBRE PRvalueE, S.A. DE C.V," },
            { value: 249, label: "6348-CAFETALEROS DE HONDURAS S DE RL CV" },
            { value: 250, label: "6349-PARTNER HERO CENTRAL AMERICA SRL CV" },
            { value: 251, label: "6350-CORPORACION ANDIFAR, S. A. DE C. V." },
            { value: 252, label: "6351-CORUMO INTERNACIONAL S DE RL DE CV" },
            { value: 253, label: "6352-AVANZA LOGISTICS SA DE CV" },
            { value: 254, label: "6353-CORPORACION ATAMAR, S.A." },
            { value: 255, label: "6354-LABORATORIOS KARNEL, S.A" },
            { value: 256, label: "6355-CALZADOS DE HONDURAS S A" },
            { value: 257, label: "6356-TELEPERFORMANCE, SOCIEDAD ANONIMA" },
            { value: 258, label: "6357-PROCESADORA DEL CARIBE S.A DE C.V." },
            { value: 259, label: "6358-SAN JUAN INNOVATION PARK SA DE CV" },
            { value: 260, label: "6359-ALTIA BUSINESS PARK S.A. DE C.V." },
            { value: 261, label: "6360-ZABA INDUSTRIES, S. DE R. L. DE C." },
            { value: 262, label: "6361-TABACO MAYA S DE RL" },
            { value: 263, label: "6362-CRC BPO SOLUTIONS S. DE R.L." },
            { value: 264, label: "6363-GRUPO ALCA, S.A. DE C.V." },
            { value: 265, label: "6364-UNION DE FINCAS CAMARONERAS SOCIEDAD ANONIMA DE CA" },
            { value: 266, label: "6365-ALTIA BUSINESS PARK SA DE CV" },
            { value: 267, label: "6366-DEL MAR APPAREL S. A." },
            { value: 268, label: "6367-POWERS ATHLETIC DE HONDURAS SOCIEDAD ANONIMA DE CA" },
            { value: 269, label: "6368-PRvalueE YARN, S. DE R.L" },
            { value: 270, label: "6369-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 271, label: "6370-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 272, label: "6371-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 273, label: "6372-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 274, label: "6373-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 275, label: "6374-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 276, label: "6375-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 277, label: "6376-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 278, label: "6377-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 279, label: "6378-EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A" },
            { value: 280, label: "6379-PLASTICOS INDUSTRIALES HONDUREÑOS SA DE CV" },
            { value: 281, label: "6380-EXPORTADORA AGRICOLA MESOAMERICANA, SOCIEDAD ANONI" },
            { value: 282, label: "6381-RESULTS HONDURAS, S.A." },
            { value: 283, label: "6382-ZONA LIBRE GREEN VALLEY INDUSTRIAL PARK SA DE CV" },
            { value: 284, label: "6383-SANTA LUCIA DEL PARAISO, S.A. DE C.V." },
            { value: 285, label: "6384-RIVERMAR LARVICULTURA S. DE R.L." },
            { value: 286, label: "6385-ACUARIUS, S DE R.L. DE C.V." },
            { value: 287, label: "6386-INDUSTRIA RESINERA BAHR, S. A." },
            { value: 288, label: "6387-SOUTHERN APPAREL CONTRACTORS S.A." },
            { value: 289, label: "6388-CORINFAR S A DE C V" },
            { value: 290, label: "6389-SOUTHERN APPAREL CONTRACTORS SA" },
            { value: 291, label: "6392-GLOBAL PRINTING SOLUTIONS DE HONDURAS SOCIEDAD ANO" },
            { value: 292, label: "9100-ZEDE MORAZAN" },
            { value: 293, label: "9101-ZEDE ORQUvalueEA" },
            { value: 294, label: "9102-ZEDE PROSPERA" },
        ],

        provincias: [
            { value: '1', label: 'BA - Buenos Aires' },
            { value: '2', label: 'CO - Córdoba' },
            { value: '3', label: 'SF - Santa Fe' },
            { value: '4', label: 'MZ - Mendoza' },
            { value: '5', label: 'TU - Tucumán' },
            { value: '6', label: 'SP - São Paulo' },
            { value: '7', label: 'RJ - Rio de Janeiro' },
            { value: '8', label: 'MG - Minas Gerais' },
            { value: '9', label: 'BA - Bahia' },
            { value: '10', label: 'RS - Rio Grande do Sul' },
            { value: '11', label: 'ON - Ontario' },
            { value: '12', label: 'QC - Quebec' },
            { value: '13', label: 'BC - British Columbia' },
            { value: '14', label: 'AB - Alberta' },
            { value: '15', label: 'MB - Manitoba' },
            { value: '16', label: 'CA - California' },
            { value: '17', label: 'TX - Texas' },
            { value: '18', label: 'FL - Florvaluea' },
            { value: '19', label: 'NY - New York' },
            { value: '20', label: 'IL - Illinois' },
            { value: '21', label: 'ENG - England' },
            { value: '22', label: 'SCT - Scotland' },
            { value: '23', label: 'WLS - Wales' },
            { value: '24', label: 'NIR - Northern Ireland' },
            { value: '25', label: 'NSW - New South Wales' },
            { value: '26', label: 'QLD - Queensland' },
            { value: '27', label: 'VIC - Victoria' },
            { value: '28', label: 'WA - Western Australia' },
            { value: '29', label: 'SA - South Australia' },
            { value: '30', label: 'MH - Maharashtra' },
            { value: '31', label: 'UP - Uttar Pradesh' },
            { value: '32', label: 'TN - Tamil Nadu' },
            { value: '33', label: 'KA - Karnataka' },
            { value: '34', label: 'GJ - Gujarat' },
            { value: '35', label: 'GD - Guangdong' },
            { value: '36', label: 'SD - Shandong' },
            { value: '37', label: 'JS - Jiangsu' },
            { value: '38', label: 'ZJ - Zhejiang' },
            { value: '39', label: 'HA - Henan' },
            { value: '40', label: 'MOW - Moscow' },
            { value: '41', label: 'SPE - Saint Petersburg' },
            { value: '42', label: 'NVS - Novosibirsk' },
            { value: '43', label: 'EKB - Yekaterinburg' },
            { value: '44', label: 'NIZ - Nizhny Novgorod' },
            { value: '45', label: 'valueF - Île-de-France' },
            { value: '46', label: 'ARA - Auvergne-Rhône-Alpes' },
            { value: '47', label: 'HDF - Hauts-de-France' },
            { value: '48', label: 'OCC - Occitanie' },
            { value: '49', label: 'NOR - Normandy' },
            { value: '50', label: 'NRW - North Rhine-Westphalia' },
            { value: '51', label: 'BY - Bavaria' },
            { value: '52', label: 'BW - Baden-Württemberg' },
            { value: '53', label: 'NI - Lower Saxony' },
            { value: '54', label: 'HE - Hesse' },
            { value: '55', label: 'LOM - Lombardy' },
            { value: '56', label: 'LAZ - Lazio' },
            { value: '57', label: 'CAM - Campania' },
            { value: '58', label: 'SIC - Sicily' },
            { value: '59', label: 'VEN - Veneto' },
            { value: '60', label: 'MAD - Madrvalue' },
            { value: '61', label: 'CAT - Catalonia' },
            { value: '62', label: 'AND - Andalusia' },
            { value: '63', label: 'VAL - Valencia' },
            { value: '64', label: 'GAL - Galicia' },
            { value: '65', label: '01 - Atlantvaluea' },
            { value: '66', label: '02 - Colon' },
            { value: '67', label: '03 - Comayagua' },
            { value: '68', label: '04 - Copan' },
            { value: '69', label: '05 - Cortes' },
            { value: '70', label: '06 - Choluteca' },
            { value: '71', label: '07 - El Paraiso' },
            { value: '72', label: '08 - Francisco Morazan' },
            { value: '73', label: '09 - Gracias a Dios' },
            { value: '74', label: '10 - Intibuca' },
            { value: '75', label: '11 - Islas de La Bahia' },
            { value: '76', label: '12 - La Paz' },
            { value: '77', label: '13 - Lempira' },
            { value: '78', label: '14 - Ocotepeque' },
            { value: '79', label: '15 - Olancho' },
            { value: '80', label: '16 - Santa Barbara' },
            { value: '81', label: '17 - Valle' },
            { value: '82', label: '18 - Yoro' },
        ],

        paises: [
            { value: 1, label: "AD-ANDORRA" },
            { value: 2, label: "AE-EMIRATOS ARABES UNvalueOS" },
            { value: 3, label: "AF-AFGANISTAN" },
            { value: 4, label: "AG-ANTIGUA Y BARBUDA" },
            { value: 5, label: "AI-ANGUILLA" },
            { value: 6, label: "AL-ALBANIA" },
            { value: 7, label: "AM-ARMENIA" },
            { value: 8, label: "AN-ANTILLAS HOLANDESAS" },
            { value: 9, label: "AO-ANGOLA" },
            { value: 10, label: "AQ-ANTARTvalueA" },
            { value: 11, label: "AR-ARGENTINA" },
            { value: 12, label: "AS-SAMOA AMERICANA" },
            { value: 13, label: "AT-AUSTRIA" },
            { value: 14, label: "AU-AUSTRALIA" },
            { value: 15, label: "AW-ARUBA" },
            { value: 16, label: "AX-ALAND, ISLAS" },
            { value: 17, label: "AZ-AZERBALIAN" },
            { value: 18, label: "BA-BOSNIA Y HERZSEGOVINA" },
            { value: 19, label: "BB-BARBADOS" },
            { value: 20, label: "BD-BANGLADESH" },
            { value: 21, label: "BE-BELGICA" },
            { value: 22, label: "BF-BURKINA FASO" },
            { value: 23, label: "BG-BULGARIA" },
            { value: 24, label: "BH-BAHREIN" },
            { value: 25, label: "BI-BURUNDI" },
            { value: 26, label: "BJ-BENIN" },
            { value: 27, label: "BL-SAINT BARTHELEMY" },
            { value: 28, label: "BM-BERMUDA" },
            { value: 29, label: "BN-BRUNEI DARUSSALAM" },
            { value: 30, label: "BO-BOLIVIA" },
            { value: 31, label: "BQ-BONAIRE, SINT EUSTATIUS AND SABA" },
            { value: 32, label: "BR-BRASIL" },
            { value: 33, label: "BS-BAHAMAS" },
            { value: 34, label: "BT-BUTAN" },
            { value: 35, label: "BV-BOUVET, ISLA" },
            { value: 36, label: "BW-BOTSWANA" },
            { value: 37, label: "BY-BIELORRUSIA" },
            { value: 38, label: "BZ-BELICE" },
            { value: 39, label: "CA-CANADA" },
            { value: 40, label: "CC-COCOS (KEELING) ISLAS" },
            { value: 41, label: "CD-CONGO, REPUBLICA DEMOCRATICA" },
            { value: 42, label: "CF-CENTROAFRICANA, REPUBLICA" },
            { value: 43, label: "CG-CONGO, REP. POPULAR DEL" },
            { value: 44, label: "CH-SUIZA" },
            { value: 45, label: "CI-COSTA DE MARFIL (COTE D'IVOIRE)" },
            { value: 46, label: "CK-COOK ISLAS" },
            { value: 47, label: "CL-CHILE" },
            { value: 48, label: "CM-CAMERUN" },
            { value: 49, label: "CN-CHINA" },
            { value: 50, label: "CO-COLOMBIA" },
            { value: 51, label: "CR-COSTA RICA" },
            { value: 52, label: "CU-CUBA" },
            { value: 53, label: "CV-CABO VERDE" },
            { value: 54, label: "CW-CURAZAO" },
            { value: 55, label: "CX-NAVvalueAD, ISLAS" },
            { value: 56, label: "CY-CHIPRE" },
            { value: 57, label: "CZ-CHECA, REPUBLICA" },
            { value: 58, label: "DE-ALEMANIA, REPUBLICA FEDERAL" },
            { value: 59, label: "DJ-DJIBOUTH" },
            { value: 60, label: "DK-DINAMARCA" },
            { value: 61, label: "DM-DOMINICA" },
            { value: 62, label: "DO-DOMINICANA, REPUBLICA" },
            { value: 63, label: "DZ-ARGELIA" },
            { value: 64, label: "EC-ECUADOR" },
            { value: 65, label: "EE-ESTONIA" },
            { value: 66, label: "EG-EGIPTO" },
            { value: 67, label: "EH-SAHARA DEL OESTE" },
            { value: 68, label: "ER-ERITREA" },
            { value: 69, label: "ES-ESPAÑA" },
            { value: 70, label: "ET-ETIOPIA" },
            { value: 71, label: "FI-FINLANDIA" },
            { value: 72, label: "FJ-FIJI" },
            { value: 73, label: "FK-FALKLAND ISLAS (MALVINAS)" },
            { value: 74, label: "FM-MICRONESIA,ESTADO FEDERAL DE" },
            { value: 75, label: "FO-FAROE, ISLAS" },
            { value: 76, label: "FR-FRANCIA" },
            { value: 77, label: "GA-GABON" },
            { value: 78, label: "GB-REINO UNvalueO (INGLATERRA, IRLANDA NORTE, ESCOCIA, GALES)" },
            { value: 79, label: "GD-GRENADA" },
            { value: 80, label: "GE-GEORGIA" },
            { value: 81, label: "GF-FRANCESA, GUINEA" },
            { value: 82, label: "GH-GHANA" },
            { value: 83, label: "GI-GIBRALTAR" },
            { value: 84, label: "GL-GROENLANDIA" },
            { value: 85, label: "GM-GAMBIA" },
            { value: 86, label: "GN-GUINEA" },
            { value: 87, label: "GP-GUADALUPE" },
            { value: 88, label: "GQ-ECUATORIAL, GUINEA" },
            { value: 89, label: "GR-GRECIA" },
            { value: 90, label: "GS-GEORGIA DEL SUR E ISLAS SAND" },
            { value: 91, label: "GT-GUATEMALA" },
            { value: 92, label: "GU-GUAN" },
            { value: 93, label: "GW-GUINEA-BISSAU" },
            { value: 94, label: "GY-GUYANA (ANTIGUA GUYANA INGLESA" },
            { value: 95, label: "HK-HONG KONG" },
            { value: 96, label: "HM-HEARD Y MC DONALD ISLAS" },
            { value: 97, label: "HN-HONDURAS" },
            { value: 98, label: "HR-CROACIA" },
            { value: 99, label: "HT-HAITI" },
            { value: 100, label: "HU-HUNGRIA" },
            { value: 101, label: "value-INDONESIA" },
            { value: 102, label: "IE-IRLANDA" },
            { value: 103, label: "IL-ISRAEL" },
            { value: 104, label: "IN-INDIA" },
            { value: 105, label: "IO-TERRITORIO BRITANICO DEL OCEANO INDICO" },
            { value: 106, label: "IQ-IRAQ" },
            { value: 107, label: "IR-IRAN, REPUBLICA ISLAMICA" },
            { value: 108, label: "IS-ISLANDIA" },
            { value: 109, label: "IT-ITALIA" },
            { value: 110, label: "JM-JAMAICA" },
            { value: 111, label: "JO-JORDANIA" },
            { value: 112, label: "JP-JAPON" },
            { value: 113, label: "KE-KENIA" },
            { value: 114, label: "KG-KIRGHIZISTAN" },
            { value: 115, label: "KH-CAMBOYA" },
            { value: 116, label: "KI-KIRIBATI" },
            { value: 117, label: "KM-COMORES" },
            { value: 118, label: "KN-SAINT KITTS AND NEVIS" },
            { value: 119, label: "KP-KOREA, REP. POPULAR DEMOCRATICA" },
            { value: 120, label: "KR-KOREA, REP. DE (KOREA DEL SUR)" },
            { value: 121, label: "KW-KUWAIT" },
            { value: 122, label: "KY-CAIMAN ISLAS" },
            { value: 123, label: "KZ-KAZAKSTAN" },
            { value: 124, label: "LA-LAOS, REPUBLICA POPULAR DEMOCRATICA" },
            { value: 125, label: "LB-LIBANO" },
            { value: 126, label: "LC-SANTA LUCIA" },
            { value: 127, label: "LI-LIECHTENSTEIN" },
            { value: 128, label: "LK-SRI LANKA (CEILAN)" },
            { value: 129, label: "LR-LIBERIA" },
            { value: 130, label: "LS-LESOTHO" },
            { value: 131, label: "LT-LITUANIA" },
            { value: 132, label: "LU-LUXEMBURGO" },
            { value: 133, label: "LV-LETONIA" },
            { value: 134, label: "LY-LIBIA ARABE JAMAHIRIYA" },
            { value: 135, label: "MA-MARRUECOS" },
            { value: 136, label: "MC-MONACO" },
            { value: 137, label: "MD-MOLDAVIA, REPUBLICA DE" },
            { value: 138, label: "ME-MONTENEGRO" },
            { value: 139, label: "MF-SAINT MARTIN (FRENCH PART)" },
            { value: 140, label: "MG-MADAGASCAR" },
            { value: 141, label: "MH-MARSHALL, ISLAS" },
            { value: 142, label: "MK-MACEDONIA, LA ANT.REP.DE YUGOS" },
            { value: 143, label: "ML-MALI" },
            { value: 144, label: "MM-MYANMAR (ANTIGUA REP. DE BIRMANIA)" },
            { value: 145, label: "MN-MONGOLIA" },
            { value: 146, label: "MO-MACAU" },
            { value: 147, label: "MP-MARIANAS SEPTENTRIONALES, ISLAS" },
            { value: 148, label: "MQ-MARTINICA" },
            { value: 149, label: "MR-MAURITANIA" },
            { value: 150, label: "MS-MONTSERRAT" },
            { value: 151, label: "MT-MALTA" },
            { value: 152, label: "MU-MAURICIOS" },
            { value: 153, label: "MV-MALDIVAS" },
            { value: 154, label: "MW-MALAWI" },
            { value: 155, label: "MX-MEXICO" },
            { value: 156, label: "MY-MALASIA" },
            { value: 157, label: "MZ-MOZAMBIQUE" },
            { value: 158, label: "NA-NAMIBIA" },
            { value: 159, label: "NC-NUEVA CALEDONIA" },
            { value: 160, label: "NE-NIGER" },
            { value: 161, label: "NF-NORFOLK, ISLAS" },
            { value: 162, label: "NG-NIGERIA" },
            { value: 163, label: "NI-NICARAGUA" },
            { value: 164, label: "NL-PAISES BAJOS" },
            { value: 165, label: "NO-NORUEGA" },
            { value: 166, label: "NP-NEPAL" },
            { value: 167, label: "NR-NAURO" },
            { value: 168, label: "NU-NIUE" },
            { value: 169, label: "NZ-NUEVA ZELANDA" },
            { value: 170, label: "OM-OMAN" },
            { value: 171, label: "PA-PANAMA" },
            { value: 172, label: "PE-PERU" },
            { value: 173, label: "PF-FRANCESA POLINESIA" },
            { value: 174, label: "PG-PAPUA NUEVA GUINEA" },
            { value: 175, label: "PH-FILIPINAS" },
            { value: 176, label: "PK-PAKISTAN" },
            { value: 177, label: "PL-POLONIA" },
            { value: 178, label: "PM-SAN PEDRO Y MIGUELON" },
            { value: 179, label: "PN-PITCAIRN" },
            { value: 180, label: "PR-PUERTO RICO" },
            { value: 181, label: "PS-TERRITORIO PALESTINO OCUPADO" },
            { value: 182, label: "PT-PORTUGAL" },
            { value: 183, label: "PW-PALAU" },
            { value: 184, label: "PY-PARAGUAY" },
            { value: 185, label: "QA-QATAR" },
            { value: 186, label: "RE-REUNION" },
            { value: 187, label: "RO-RUMANIA" },
            { value: 188, label: "RS-SERBIA" },
            { value: 189, label: "RU-RUSA, FEDERACION" },
            { value: 190, label: "RW-RUANDA" },
            { value: 191, label: "SA-SAUDITA ARABIA" },
            { value: 192, label: "SB-SOLOMON, ISLAS" },
            { value: 193, label: "SC-SEYCHELLES, ISLAS" },
            { value: 194, label: "SD-SUDAN" },
            { value: 195, label: "SE-SUECIA" },
            { value: 196, label: "SG-SINGAPUR" },
            { value: 197, label: "SH-SANTA HELENA" },
            { value: 198, label: "SI-ESLOVENIA" },
            { value: 199, label: "SJ-SVALBARD AND JAN MAYEN ISLAS" },
            { value: 200, label: "SK-ESLOVAKIA" },
            { value: 201, label: "SL-SIERRA LEONA" },
            { value: 202, label: "SM-SAN MARINO" },
            { value: 203, label: "SN-SENEGAL" },
            { value: 204, label: "SO-SOMALIA" },
            { value: 205, label: "SR-SURINAM (GUAYANA HOLANDESAS)" },
            { value: 206, label: "SS-SUDAN DEL SUR" },
            { value: 207, label: "ST-SAO TOME Y PRINCIPE" },
            { value: 208, label: "SV-EL SALVADOR" },
            { value: 209, label: "SX-SINT MAARTEN (DUTCH PART)" },
            { value: 210, label: "SY-SIRIA, REPUBLICA ARABE" },
            { value: 211, label: "SZ-SUAZILANDIA" },
            { value: 212, label: "TC-TURCOS Y CAICOS ISLAS" },
            { value: 213, label: "TD-CHAD" },
            { value: 214, label: "TF-FRANCESES, TERRITORIOS DEL SURESTE" },
            { value: 215, label: "TG-TOGO" },
            { value: 216, label: "TH-TAILANDIA" },
            { value: 217, label: "TJ-TADJIKISTAN" },
            { value: 218, label: "TK-TOKELAU" },
            { value: 219, label: "TL-TIMOR DEL ESTE" },
            { value: 220, label: "TM-TURKMENISTAN" },
            { value: 221, label: "TN-TUNISIA" },
            { value: 222, label: "TO-TONGA" },
            { value: 223, label: "TR-TURQUIA" },
            { value: 224, label: "TT-TRINvalueAD Y TOBAGO" },
            { value: 225, label: "TV-TUVALU" },
            { value: 226, label: "TW-TAIWAN, PROVINCIA CHINA DE" },
            { value: 227, label: "TZ-TANZANIA, REPUBLICA UNvalueA DE" },
            { value: 228, label: "UA-UCRANIA" },
            { value: 229, label: "UG-UGANDA" },
            { value: 230, label: "UM-ISLAS ULTRAMARINAS MENORES (EEUU)" },
            { value: 231, label: "US-ESTADOS UNvalueOS" },
            { value: 232, label: "UY-URUGUAY" },
            { value: 233, label: "UZ-UZBEKISTAN" },
            { value: 234, label: "VA-SANTA SEDE (CIUDAD DEL VATICANO)" },
            { value: 235, label: "VC-SAN VICENTE Y LAS GRANADINAS" },
            { value: 236, label: "VE-VENEZUELA" },
            { value: 237, label: "VG-VIRGENES, ISLAS (BRITANICAS)" },
            { value: 238, label: "VI-VIRGENES, ISLAS (ESTADOS UNvalueOS)" },
            { value: 239, label: "VN-VIETNAM" },
            { value: 240, label: "VU-VANUATU" },
            { value: 241, label: "WF-WALLIS Y FUTUNA, ISLAS" },
            { value: 242, label: "WS-SAMOA" },
            { value: 243, label: "YE-YEMEN" },
            { value: 244, label: "YT-MAYOTTE" },
            { value: 245, label: "ZA-SURAFRICA" },
            { value: 246, label: "ZM-ZAMBIA" },
            { value: 247, label: "ZW-ZIMBABWE" },
        ],
        nivelComercia: [
            { value: '1', label: 'DIS - DISTRIBUvalueOR' },
            { value: '2', label: 'MAY - MAYORISTA' },
            { value: '3', label: 'MIN - MINORISTA' },
            { value: '4', label: 'OTR - OTROS' },
        ],

        condicionComercia: [
            { value: '5', label: 'PR-Productor' },
            { value: '6', label: 'RV-Revendedor' },
            { value: '7', label: 'DT-Distribuvalueor' },
            { value: '8', label: 'FB-Fabricante' },
            { value: '9', label: 'MY-Mayorista' },
            { value: '10', label: 'OT-Otro' },
        ],

        tipoIntermediario: [
            { value: '1', label: 'BR-BROKER' },
            { value: '2', label: 'CC-COMISIONISTA COMPRA' },
            { value: '3', label: 'CO-CORREDOR' },
            { value: '4', label: 'CV-COMISIONISTA VENTA' },
            { value: '5', label: 'OT-OTRO' },
        ],

        incoterm: [
            { value: '1', label: 'CFR-COSTO Y FLETE' },
            { value: '2', label: 'CIF-COSTO,SEGURO Y FLETE' },
            { value: '3', label: 'CIP-TRANSPORTE Y SEGURO' },
            { value: '4', label: 'CPT-TRANSPORTE PAGADO' },
            { value: '5', label: 'DAF-ENTREGAS EN FRONTERA' },
            { value: '6', label: 'DAP-ENTREGA EN LUGAR' },
            { value: '7', label: 'DDP-DERECHOS PAGADOS' },
            { value: '8', label: 'DDU-DERECHOS NO PAGADOS' },
            { value: '9', label: 'DEQ-ENTRGADAS EN MUELLE' },
            { value: '10', label: 'DES-ENTREGA SOBRE BUQUE' },
            { value: '11', label: 'DPU-ENTREGADA EN LUGAR DESCARGADA' },
            { value: '12', label: 'EXW-EN FABRICA' },
            { value: '13', label: 'FAS-LIBRE COSTADO BUQUE' },
            { value: '14', label: 'FCA-FRANCO TRANSPORTISTA' },
            { value: '15', label: 'FOB-LIBRE PUESTA A BORDO' },
        ],

        formaEnvio: [
            { value: '1', label: 'FR-FRACCIONADO' },
            { value: '2', label: 'OT-OTRO' },
            { value: '3', label: 'PR-PARCIAL' },
            { value: '4', label: 'TT-TOTAL' },
        ],

        formaPago: [
            { value: '2', label: 'CARTA DE CREDITO' },
            { value: '1', label: 'CHEQUE BANCARIO/CHEQUE PERSONAL' },
            { value: '3', label: 'EFECTIVO' },
            { value: '4', label: 'GIRO BANCARIO' },
            { value: '5', label: 'OTRO' },
            { value: '6', label: 'PAGO ANTICIPADO' },
            { value: '7', label: 'PAGO ELECTRONICO' },
            { value: '9', label: 'TARJETA DE CREDITO' },
            { value: '8', label: 'TRANSFERENCIA BANCARIA' },
        ],

        lugarEmbarque: [
            { value: '1', label: 'ADALV-ANDORRA LA VELLA' },
            { value: '2', label: 'ADCAN-CANILLO' },
            { value: '3', label: 'ADEAC-ESCAS' },
            { value: '4', label: 'ADENC-ENCAMP' },
            { value: '5', label: 'ADESC-ESCALDES-ENGORDANY' },
            { value: '6', label: 'ADFMO-LA FARGA DE MOLES' },
            { value: '7', label: 'ADLMA-LA MASSANA' },
            { value: '8', label: 'ADORD-ORDINO' },
            { value: '9', label: 'ADPAS-PAS DE LA CASA' },
            { value: '10', label: 'ADSCO-SANTA COLOMA' },
            { value: '11', label: 'ADSJL-SANT JULIA DE LORIA' },
            { value: '12', label: 'AEAAN-AL AIN' },
            { value: '13', label: 'AEABU-ABU AL BUKHOOSH' },
            { value: '14', label: 'AEAJM-AJMAN' },
            { value: '15', label: 'AEAJP-AL JEER PORT' },
            { value: '16', label: 'AEALB-AL BARSHA' },
            { value: '17', label: 'AEALQ-AL QUOZ' },
            { value: '18', label: 'AEALS-AL SUFOUH' },
            { value: '19', label: 'AEAMF-MUSSAFAH' },
            { value: '20', label: 'AEAMU-ABU MUSA' },
            { value: '21', label: 'AEARP-AHMED BIN RASHvalue PORT' },
            { value: '22', label: 'AEARZ-ARZANAH ISLAND' },
            { value: '23', label: 'AEAUH-ABU DHABI' },
            { value: '24', label: 'AEDAS-DAS ISLAND' },
            { value: '25', label: 'AEDBI-AL MAFRAQ' },
            { value: '26', label: 'AEDBP-DIBBA' },
            { value: '27', label: 'AEDER-DEIRA' },
            { value: '28', label: 'AEDHF-AL DHAFRA' },
            { value: '29', label: 'AEDUJ-THE PALM JUMEIRAH' },
            { value: '30', label: 'AEDUY-RAS ZUBBAYA (RAS DUBAYYAH)' },
            { value: '31', label: 'AEDWC-DUBAI WORLD CENTRAL APT' },
            { value: '32', label: 'AEDXB-DUBAI' },
            { value: '33', label: 'AEEND-ESNNAD' },
            { value: '34', label: 'AEFAT-FATEH TERMINAL' },
            { value: '35', label: 'AEFJR-AL FUJAYRAH' },
            { value: '36', label: 'AEFMZ-MUSAFA' },
            { value: '37', label: 'AEFRP-FREE PORT' },
            { value: '38', label: 'AEHAB-HABSHAN' },
            { value: '39', label: 'AEHAM-AL HAMRIYAH' },
            { value: '40', label: 'AEHAT-HATTA' },
            { value: '41', label: 'AEHIL-HAIL' },
            { value: '42', label: 'AEHSN-HASSYAN' },
            { value: '43', label: 'AEHTL-HULAYLAH TERMINAL' },
            { value: '44', label: 'AEHZP-HAMRIYA FREE ZONE PORT' },
            { value: '45', label: 'AEIND-INDOOROODILLY' },
            { value: '46', label: 'AEJAZ-AL JAZEERA PORT' },
            { value: '47', label: 'AEJEA-JEBEL ALI' },
            { value: '48', label: 'AEJED-JEBEL DHANNA' },
            { value: '49', label: 'AEJYH-JUMAYRAH' },
            { value: '50', label: 'AEKHA-KHALvalueIA' },
            { value: '51', label: 'AEKHL-MINA KHALIFA/ABU DHABI' },
            { value: '52', label: 'AEKLB-KALBA' },
            { value: '53', label: 'AEKLF-KHOR AL FAKKAN' },
            { value: '54', label: 'AEMAS-MASFUT' },
            { value: '55', label: 'AEMBS-MUBARRAS ISLAND' },
            { value: '56', label: 'AEMKH-MINA KHALvalue' },
            { value: '57', label: 'AEMRP-MINA RASHvalue PORT' },
            { value: '58', label: 'AEMSA-MINA SAQR' },
            { value: '59', label: 'AEMUB-MUBAREK TERMINAL' },
            { value: '60', label: 'AEMZD-MINA ZAYED/ABU DHABI' },
            { value: '61', label: 'AENHD-MINHAD' },
            { value: '62', label: 'AEOFJ-OFFSHORE FUJAIRAH' },
            { value: '63', label: 'AEPRA-PORT RASHvalue' },
            { value: '64', label: 'AEQIW-UMM AL QAIWAIN' },
            { value: '65', label: 'AEQWE-JEBEL ALI FREE ZONE' },
            { value: '66', label: 'AERAK-RAS AL KHOR' },
            { value: '67', label: 'AEREI-REEM ISLAND' },
            { value: '68', label: 'AERFA-MIRFA' },
            { value: '69', label: 'AERKP-RAK KHOR PORT' },
            { value: '70', label: 'AERKT-RAS AL KHAIMAH' },
            { value: '71', label: 'AERMC-RAK MARITIME CITY' },
            { value: '72', label: 'AERUW-AR RUWAYS' },
            { value: '73', label: 'AERWP-RUWAIS PORT' },
            { value: '74', label: 'AESHJ-SHARJAH' },
            { value: '75', label: 'AESvalue-SADIYAT ISLAND' },
            { value: '76', label: 'AESIL-SILA' },
            { value: '77', label: 'AESRT-STEVEN ROCK TERMINAL' },
            { value: '78', label: 'AESWE-SWAIHAN' },
            { value: '79', label: 'AEULR-UMM AL NAR' },
            { value: '80', label: 'AEVHT-VOPAK HORIZION TERMINAL' },
            { value: '81', label: 'AEYAS-YAS ISLAND' },
            { value: '82', label: 'AEZUR-ZIRKU ISLAND' },
            { value: '83', label: 'AFASH-ALI SHIRZAYI' },
            { value: '84', label: 'AFBAG-BAGRAM' },
            { value: '85', label: 'AFBEP-BAZAR-E-PANJWAI' },
            { value: '86', label: 'AFBIN-BAMIAN' },
            { value: '87', label: 'AFBST-BOST' },
            { value: '88', label: 'AFCBN-CAMP BASTION' },
            { value: '89', label: 'AFCCN-CHAGHCHARAN' },
            { value: '90', label: 'AFCDW-CAMP DWYER' },
            { value: '91', label: 'AFCLN-CAMP LEATHERNECK' },
            { value: '92', label: 'AFCSO-CAMP SALERNO' },
            { value: '93', label: 'AFCWO-CAMP WOLVERINE' },
            { value: '94', label: 'AFDAZ-DARWAZ' },
            { value: '95', label: 'AFDHD-DEHDADI' },
            { value: '96', label: 'AFFAH-FARAH' },
            { value: '97', label: 'AFFBD-FAIZABAD' },
            { value: '98', label: 'AFFRO-FOB FRONTENAC' },
            { value: '99', label: 'AFGAR-GARDIZ' },
            { value: '100', label: 'AFGRG-GARDEZ' },
            { value: '101', label: 'AFGZI-GHAZNI' },
            { value: '102', label: 'AFHEA-HERAT' },
            { value: '103', label: 'AFHRT-HAIRATAN' },
            { value: '104', label: 'AFIMZ-NIMROZ' },
            { value: '106', label: 'AFJAA-JALALABAD' },
            { value: '107', label: 'AFKBL-KABUL' },
            { value: '108', label: 'AFKDH-KANDAHAR' },
            { value: '109', label: 'AFKHO-KHOWST' },
            { value: '110', label: 'AFKHT-KHOST' },
            { value: '111', label: 'AFKMU-KAMU' },
            { value: '112', label: 'AFKUR-KURAN-O-MUNJAN' },
            { value: '113', label: 'AFKWH-KHWAHAN' },
            { value: '114', label: 'AFKWT-KHOWST' },
            { value: '115', label: 'AFLAG-LASHKAR GAH' },
            { value: '116', label: 'AFLQN-QALA NAU' },
            { value: '117', label: 'AFMAS-MASHAD' },
            { value: '118', label: 'AFMEH-MEHTAR LAM' },
            { value: '119', label: 'AFMEY-MEYDAN' },
            { value: '120', label: 'AFMMZ-MAIMANA' },
            { value: '121', label: 'AFMWD-MAIWAND' },
            { value: '122', label: 'AFMZR-MAZAR-I-SHARIF' },
            { value: '123', label: 'AFORG-ORGUN-E KALAN' },
            { value: '124', label: 'AFPEC-POL-E CHARKHI' },
            { value: '125', label: 'AFPSD-PASABAND' },
            { value: '126', label: 'AFQAM-QASIM' },
            { value: '127', label: 'AFQLT-QALAT' },
            { value: '129', label: 'AFRKH-TORKHAM' },
            { value: '130', label: 'AFRMD-FOB RAMROD' },
            { value: '131', label: 'AFSBF-SARDEH BAND' },
            { value: '132', label: 'AFSBK-SPIN BOLDAK' },
            { value: '133', label: 'AFSDD-SHINDAND' },
            { value: '134', label: 'AFSGA-SHEGHNAN' },
            { value: '135', label: 'AFSHE-SHERHAN-BANDAR' },
            { value: '136', label: 'AFSHK-FOB SHANK' },
            { value: '137', label: 'AFSRO-SHARONA' },
            { value: '138', label: 'AFTGH-TORGHUNDI' },
            { value: '139', label: 'AFTII-TIRINKOT' },
            { value: '140', label: 'AFTKO-TARIN KOWT' },
            { value: '141', label: 'AFTOW-TOWRAGHONDI' },
            { value: '142', label: 'AFTQN-TALUQAN' },
            { value: '143', label: 'AFUND-KUNDUZ' },
            { value: '144', label: 'AFURN-URGOON' },
            { value: '145', label: 'AFURZ-URUZGAN' },
            { value: '146', label: 'AFZAJ-ZARANJ' },
            { value: '147', label: 'AFZHA-ZHARI DASHT' },
            { value: '148', label: 'AGANU-ANTIGUA' },
            { value: '149', label: 'AGBBQ-BARBUDA' },
            { value: '150', label: 'AGFAM-FALMOUTH' },
            { value: '153', label: 'AIAXA-ANGUILLA' },
            { value: '154', label: 'AIBLP-BLOWING POINT' },
            { value: '155', label: 'AICRH-CROCUS HILL' },
            { value: '156', label: 'AIFOR-THE FOREST' },
            { value: '157', label: 'AIMBB-MEADS BAY BEACH' },
            { value: '158', label: 'AIRBY-ROAD BAY' },
            { value: '159', label: 'AIROA-THE ROAD' },
            { value: '160', label: 'AISOM-SOMBRERO' },
            { value: '161', label: 'AIVAL-THE VALLEY' },
            { value: '162', label: 'AIWLL-WALL BLAKE' },
            { value: '163', label: 'ALARG-ARGYROKASTRO' },
            { value: '164', label: 'ALBQE-BULQIZË' },
            { value: '165', label: 'ALBRT-BERAT' },
            { value: '166', label: 'ALBUT-BUTRINT' },
            { value: '167', label: 'ALDRZ-DURRES (DURAZZO)' },
            { value: '168', label: 'ALFIE-FIER' },
            { value: '169', label: 'ALFUS-FUSHE ARREZ' },
            { value: '170', label: 'ALGOK-GJIROKASTËR' },
            { value: '171', label: 'ALHMR-HIMARE' },
            { value: '172', label: 'ALKKU-KUKËS' },
            { value: '173', label: 'ALKRC-KORCË' },
            { value: '174', label: 'ALLUS-LUSHNJË' },
            { value: '175', label: 'ALLZE-LEZHE' },
            { value: '176', label: 'ALMBR-MBRESHTAN' },
            { value: '177', label: 'ALMIL-MILOT' },
            { value: '178', label: 'ALNPP-ELBASAN' },
            { value: '179', label: 'ALROM-ROMANO PORT' },
            { value: '180', label: 'ALSAR-SARANDE' },
            { value: '181', label: 'ALSHG-SHENGJIN' },
            { value: '182', label: 'ALSHK-SHKODER' },
            { value: '183', label: 'ALSHZ-SHKOZET' },
            { value: '184', label: 'ALTEN-TENES' },
            { value: '185', label: 'ALTIA-TIRANA' },
            { value: '186', label: 'ALVOA-VALONA (VLORE,VLONE)' },
            { value: '187', label: 'ALVOR-VORE' },
            { value: '188', label: 'AMABO-ABOVYAN' },
            { value: '189', label: 'AMAHU-AKHURYAN' },
            { value: '190', label: 'AMARA-ARARAT' },
            { value: '191', label: 'AMARG-ARAGATSOTN' },
            { value: '192', label: 'AMARM-MASIS' },
            { value: '193', label: 'AMARV-ARMAVIR' },
            { value: '194', label: 'AMASH-ASHTARAK' },
            { value: '195', label: 'AMA3A-APARAN' },
            { value: '196', label: 'AMBRD-BERD' },
            { value: '197', label: 'AMBYU-BYUREGHAVAN' },
            { value: '198', label: 'AMDIL-DILIJAN' },
            { value: '199', label: 'AMEVN-YEREVAN' },
            { value: '200', label: 'AMEZN-ECMIADZIN' },
        ],

        moenda: [
            { value: '1', label: 'EUR-COMUNvalueAD EUROPEA, EURO' },
            { value: '2', label: 'HNL-HONDURAS, LEMPIRA' },
            { value: '3', label: 'USD-DOLAR NORTEAMERICANO' },
            { value: '4', label: 'AED-EMIRATOS ARABES UNvalueOS, DIRHAM' },
            { value: '5', label: 'AFN-AFGANISTAN, AFGANI' },
            { value: '6', label: 'ALL-ALBANIA, LEK' },
            { value: '7', label: 'AMD-ARMENIA, DRAM ARMENIO' },
            { value: '8', label: 'ANG-HOLANDESAS ANTILLAS, FLORIN ANTILLANO NEERLANDES' },
            { value: '9', label: 'AOA-ANGOLA, KWANZA' },
            { value: '10', label: 'ARS-ARGENTINA, PESO ARGENTINO' },
            { value: '11', label: 'AUD-AUSTRALIA, DOLAR AUSTRALIANO' },
            { value: '12', label: 'AWG-ARUBA, FLORIN ARUBEÑO' },
            { value: '13', label: 'AZN-AZERBALIAN, MANAT AZERBAIYANO' },
            { value: '14', label: 'BAM-BOSNIA HERZSEGOVINA, MARCO CONVERTIBLE' },
            { value: '15', label: 'BBD-BARBADOS, DOLAR DE BARBADOS' },
            { value: '16', label: 'BDT-BANGLADESH, TAKA' },
            { value: '17', label: 'BGN-BULGARIA, LEV BULGARO' },
            { value: '18', label: 'BHD-BAHREIN, DINAR BAREINI' },
            { value: '19', label: 'BIF-BURUNDI, FRANCO DE BURUNDI' },
            { value: '20', label: 'BMD-BARMUDA, DOLAR BERMUDEÑO' },
            { value: '21', label: 'BND-BRUNEI, DOLAR DE BRUNEI' },
            { value: '22', label: 'BOB-BOLIVIA, BOLIVIANO' },
            { value: '23', label: 'BRL-BRASIL, REAL BRASILEÑO' },
            { value: '24', label: 'BSD-BAHAMAS, DOLAR BAHAMEÑO' },
            { value: '25', label: 'BTN-BUTAN, NGULTRUM' },
            { value: '26', label: 'BWP-BOTSWANA, PULA' },
            { value: '27', label: 'BYR-BIELORRUSIA, RUBLO BIELORRUSO' },
            { value: '28', label: 'BZD-BELICE, DOLAR BELICEÑO' },
            { value: '29', label: 'CAD-CANADA, DOLAR CANADIENSE' },
            { value: '30', label: 'CDF-CONGO, REPUBLICA DEMOCRATICA, FRANCO CONGOLEÑO' },
            { value: '31', label: 'CHF-SUIZA, FRANCO SUIZO' },
            { value: '32', label: 'CLP-CHILE, PESO CHILENO' },
            { value: '33', label: 'CNY-CHINA, YUAN CHINO' },
            { value: '34', label: 'COP-COLOMBIA, PESO COLOMBIANO' },
            { value: '35', label: 'CRC-COSTA RICA, COLON COSTARRICENSE' },
            { value: '36', label: 'CUC-CUBA, PESO CONVERTIBLE' },
            { value: '37', label: 'CUP-CUBA, PESO CUBANO' },
            { value: '38', label: 'CVE-CABO VERDE, ESCUDO CABOVERDIANO' },
            { value: '39', label: 'CZK-CHECA REPUBLICA, CORONA CHECA' },
            { value: '40', label: 'DJF-DJIBOUTH, FRANCO YIBUTIANO' },
            { value: '41', label: 'DKK-DINAMARCA, CORONA DANESA' },
            { value: '42', label: 'DOP-DOMINICANA REPUBLICA, PESO DOMINICANO' },
            { value: '43', label: 'DZD-ARGELIA, DINAR ARGELINO' },
            { value: '44', label: 'EGP-EGIPTO, LIBRA EGIPCIA' },
            { value: '45', label: 'ERN-ERITREA, NAKFA' },
            { value: '46', label: 'ETB-ETIOPIA, BIRR ETIOPE' },
            { value: '47', label: 'FJD-FIJI, DOLAR FIYIANO' },
            { value: '48', label: 'FKP-ISLAS MALVINAS, LIBRA MALVINENSE' },
            { value: '49', label: 'GBP-REINO UNvalueO, LIBRA ESTERLINA' },
            { value: '50', label: 'GEL-GEORGIA, LARI' },
            { value: '51', label: 'GHS-GHANA, CEDI GHANES' },
            { value: '52', label: 'GIP-GIBRALTAR, LIBRA DE GIBRALTAR' },
            { value: '53', label: 'GMD-GAMBIA, DALASI' },
            { value: '54', label: 'GNF-GUINEA, FRANCO GUINEANO' },
            { value: '55', label: 'GTQ-GUATEMALA, QUETZAL' },
            { value: '56', label: 'GYD-GUYANA, DOLAR GUYANES' },
            { value: '57', label: 'HKD-HONG KONG, DOLAR DE HONG KONG' },
            { value: '58', label: 'HRK-CROACIA, KUNA' },
            { value: '59', label: 'HTG-HAITI, GOURDE' },
            { value: '60', label: 'HUF-HUNGRIA, FORINTO' },
            { value: '61', label: 'valueR-INDONESIA, RUPIA INDONESIA' },
            { value: '62', label: 'ILS-ISRAEL, NUEVO SHEQUEL ISRAELI' },
            { value: '63', label: 'INR-INDIA, RUPIA INDIA' },
            { value: '64', label: 'IQD-IRAQ, DINAR IRAQUI' },
            { value: '65', label: 'IRR-IRAN, RIAL IRANI' },
            { value: '66', label: 'ISK-ISLANDIA, CORONA ISLANDESA' },
            { value: '67', label: 'JMD-JAMAICA, DOLAR JAMAIQUINO' },
            { value: '68', label: 'JOD-JORDANIA, DINAR JORDANO' },
            { value: '69', label: 'JPY-JAPON, YEN' },
            { value: '70', label: 'KES-KENIA, CHELIN KENIANO' },
            { value: '71', label: 'KGS-KIRGHIZISTAN, SOM' },
            { value: '72', label: 'KHR-CAMBOYA, RIEL' },
            { value: '73', label: 'KMF-COMORES, FRANCO COMORENSE' },
            { value: '74', label: 'KPW-KOREA, REPUBLICA POPULAR, WON NORCOREANO' },
            { value: '75', label: 'KRW-KOREA, REPUBLICA DEMOCRATICA, WON' },
            { value: '76', label: 'KWD-KUWAIT, DINAR KUWAITI' },
            { value: '77', label: 'KYD-CAIMAN ISLAS, DOLAR DE LAS ISLAS CAIMAN' },
            { value: '78', label: 'KZT-KAZAKSTAN, TENGE' },
            { value: '79', label: 'LAK-LAOS, REPUBLICA POPULAR DEMOCRATICA, KIP' },
            { value: '80', label: 'LBP-LIBANO, LIBRA LIBANESA' },
            { value: '81', label: 'LKR-SRI LANKA, RUPIA DE SRI LANKA' },
            { value: '82', label: 'LRD-LIBERIA, DOLAR LIBERIANO' },
            { value: '83', label: 'LSL-LESOTHO, LOTI' },
            { value: '84', label: 'LYD-LIBIA ARABE, DINAR LIBIO' },
            { value: '85', label: 'MAD-MARRUECOS, DIRHAM MARROQUI' },
            { value: '86', label: 'MDL-MOLDAVIA, REPUBLICA DE, LEU MOLDAVO' },
            { value: '87', label: 'MGA-MADAGASCAR, ARIARY MALGACHE' },
            { value: '88', label: 'MKD-MACEDONIA, DENAR' },
            { value: '89', label: 'MMK-MYANMA, KYAT' },
            { value: '90', label: 'MNT-MONGOLIA, TUGRIK' },
            { value: '91', label: 'MOP-MACAU, PATACA' },
            { value: '92', label: 'MRO-MAURITANIA, UQUIYA' },
            { value: '93', label: 'MUR-MAURICIOS, RUPIA DE MAURICIO' },
            { value: '94', label: 'MVR-MALDIVAS, RUFIYAA' },
            { value: '95', label: 'MWK-MALAWI, KWACHA' },
            { value: '96', label: 'MXN-MEXICO, PESO MEXICANO' },
            { value: '97', label: 'MYR-MALASIA, RINGGIT MALAYO' },
            { value: '98', label: 'MZN-MOZAMBIQUE, METICAL MOZAMBIQUEÑO' },
            { value: '99', label: 'NAD-NAMIBIA, DOLAR NAMIBIO' },
            { value: '100', label: 'NGN-NIGERIA, NAIRA' },
            { value: '101', label: 'NIO-NICARAGUA, CORDOBA' },
            { value: '102', label: 'NOK-NORUEGA, CORONA NORUEGA' },
            { value: '103', label: 'NPR-NEPAL, RUPIA NEPALI' },
            { value: '104', label: 'NZD-NUEVA ZELANDA, DOLAR NEOZELANDES' },
            { value: '105', label: 'OMR-OMAN, RIAL OMANI' },
            { value: '106', label: 'PAB-PANAMA, BALBOA' },
            { value: '107', label: 'PEN-PERU, SOL PERUANO' },
            { value: '108', label: 'PGK-PAPUA NUEVA GUINEA, KINA' },
            { value: '109', label: 'PHP-FILIPINAS, PESO FILIPINO' },
            { value: '110', label: 'PKR-PAKISTAN, RUPIA PAKISTANI' },
            { value: '111', label: 'PLN-POLONIA, ZLOTY' },
            { value: '112', label: 'PYG-PARAGUAY, GUARANI' },
            { value: '113', label: 'QAR-QATAR, RIYAL QATARI' },
            { value: '114', label: 'RON-RUMANIA, LEU RUMANO' },
            { value: '115', label: 'RSD-SERBIA, DINAR SERBIO' },
            { value: '116', label: 'RUB-RUSA FEDERACION, RUBLO RUSO' },
            { value: '117', label: 'RWF-RUANDA, FRANCO RUANDES' },
            { value: '118', label: 'SAR-SAUDITA ARABIA, RIYAL SAUDI' },
            { value: '119', label: 'SBD-SOLOMON ISLAS, DOLAR DE LAS ISLAS SALOMON' },
            { value: '120', label: 'SCR-SEYCHELLES ISLAS, RUPIA SEYCHELENSE' },
            { value: '121', label: 'SDG-SUDAN, DINAR SUDANES' },
            { value: '122', label: 'SEK-SUECIA, CORONA SUECA' },
            { value: '123', label: 'SGD-SINGAPUR, DOLAR DE SINGAPUR' },
            { value: '124', label: 'SHP-SANTA HELENA, LIBRA DE SANTA ELENA' },
            { value: '125', label: 'SLL-SIERRA LEONA, LEONE' },
            { value: '126', label: 'SOS-SOMALIA, CHELIN SOMALI' },
            { value: '127', label: 'SRD-SURINAM, DOLAR SURINAMES' },
            { value: '128', label: 'SSP-SUDAN DEL SUR, LIBRA SURSUDANESA' },
            { value: '129', label: 'STD-SAO TOME Y PRINCIPE, DOBRA' },
            { value: '130', label: 'SYP-SIRIA REPUBLICA ARABE, LIBRA SIRIA' },
            { value: '131', label: 'SZL-SUAZILANDIA, LILANGENI' },
            { value: '132', label: 'THB-TAILANDIA, BAHT' },
            { value: '133', label: 'TJS-TADJIKISTAN, SOMONI TAYIKO' },
            { value: '134', label: 'TMT-TURKMENISTAN, MANAT TURCOMANO' },
            { value: '135', label: 'TND-TUNISIA, DINAR TUNECINO' },
            { value: '137', label: 'TRY-TURQUIA, LIRA TURCA' },
            { value: '138', label: 'TTD-TRINvalueAD Y TOBAGO, DOLAR DE TRINvalueAD Y TOBAGO' },
            { value: '139', label: 'TWD-TAIWAN, NUEVO DOLAR TAIWANES' },
            { value: '140', label: 'TZS-TANZANIA, CHELIN TANZANO' },
            { value: '141', label: 'UAH-UCRANIA, GRIVNA' },
            { value: '142', label: 'UGX-UGANDA, CHELIN UGANDES' },
            { value: '143', label: 'UYU-URUGUAY, PESO URUGUAYO' },
            { value: '144', label: 'UZS-UZBEKISTAN, SOM UZBEKO' },
            { value: '145', label: 'VEF-VENEZUELA, BOLIVAR' },
            { value: '146', label: 'VND-VIETNAM, DONG VIETNAMITA' },
            { value: '147', label: 'VUV-VANUATU, VATU' },
            { value: '148', label: 'WST-SAMOA, TALA' },
            { value: '149', label: 'XAF-FRANCO CFA DE AFRICA CENTRAL' },
            { value: '150', label: 'XCD-DOLAR DEL CARIBE ORIENTAL' },
            { value: '151', label: 'XOF-FRANCO CFA DE AFRICA OCCvalueENTAL' },
            { value: '152', label: 'XPF-FRANCO CFP' },
            { value: '153', label: 'XSU-SUCRE' },
            { value: '154', label: 'YER-YEMEN, RIAL YEMENI' },
            { value: '155', label: 'ZAR-SURAFRICA, RAND' },
            { value: '156', label: 'ZMW-ZAMBIA, KWACHA ZAMBIANO' },
            { value: '157', label: 'ZWL-ZIMBABWE, DOLAR ZIMBABUENSE' },
            { value: '158', label: '546-aLEX' },
        ],
    }

    return data

}

export default DatosDDLs